# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch (usually main or master)
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Updated to Node 22 LTS
          # Remove the cache option since bun caching isn't supported

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          cache: true  # This enables Bun's built-in caching

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Deploy to localfirstbookmarkr.github.io repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          # This is the key part: it deploys to a different repository
          external_repository: localfirstbookmarkr/localfirstbookmarkr.github.io
          # The token we set up in Step 2
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          # This should match your build output directory
          publish_dir: ./dist
          # Force-push to the target branch to keep history clean
          force_orphan: true
          # The branch of the TARGET repo (localmark.github.io) to push to
          publish_branch: main